# Generated by Django 4.2.6 on 2023-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
